<footer>

  <div class="footer_container">


      <a href="index.php"><img class="footer_logo" src="img/logo.png" alt="footer_logo.png"></a>
        <br>
        <br>
      <table>
        <tr>
          <td>
            <a class="nav-link nav_footer" href="index.php">Home</a>
            <a class="nav-link nav_footer" href="fleet.php">Fleet</a>
            <a class="nav-link nav_footer" href="location.php">Fleet</a>
            <a class="nav-link nav_footer" href="about.php">About Us</a>
            <a class="nav-link nav_footer" href="contact.php">Contact Us</a>
          </td>
          <td style="width: 210px;">
            <a class="nav-link nav_footer" href="#">Site Map</a>
            <a class="nav-link nav_footer" href="#">Privacy Policys</a>
            <a class="nav-link nav_footer" href="#">Pick Up & Drop Off</a>
            <a class="nav-link nav_footer" href="#">Terms & Conditions</a>
          </td>
        </tr>
      </table>



  </div>
</footer>
</body>
</html>
