<footer>

  <div class="footer_container">


      <a href="index.php"><img class="footer_logo" src="http://mcm.mccrew.com.au/img/logo.png" alt="footer_logo.png"></a>
        <br>
        <br>
      <table>
        <tr>
          <td>
            <a class="nav-link nav_footer" href="add.php">Add a Car</a>
            <a class="nav-link nav_footer" href="remove.php">Remove a Car</a>
          </td>
        </tr>
      </table>



  </div>
</footer>
</body>
</html>
